import EFX.K3DEImprove

/-!
# Draft and Exchange: the ring family needs `k` exposure arcs (paper/k3-simple §6.4)

The paragraph "No bounded number of exposure arcs suffices" of `paper/k3-simple/long.tex` §6.4 (the family of
`k3/simplify/po/potential/NOTES.md` §7, generated by `gen_tree(k, d, shared)` in
`k3/simplify/po/potential/test_exchange.py` and in `paper/k3-simple/examples/check_examples.py` [5]): valid states with
`k` free agents in a ring, in which no free agent is a valid absorber and every cycle of the exchange digraph `D⁺`
uses exactly `k` exposure arcs. Everything is proved for all parameters; nothing is checked by evaluation.

**The exchange digraph** (§5, Definition exchange digraph; for any state). `NeedArc j j'` (Definition need digraph):
`j`, `j'` listed outside `up`, `j` holds a single good that `j'` needs. `ExpArc o x`: `o` is free and holds a good, and
`x` is exposed for `o` (`EFX.DE.Exposed`); its label is the protecting good `EFX.DE.hOf x`. `Arc` is either. A cycle
(`DCycle`) is a nonempty list of distinct agents, each joined to the next, and the last to the first, by an arc
(`cycArcs`); `nExp` counts its exposure arcs and `labels` lists their labels (distinct labels: `labels` has no
repetition). `DCycle.two_le`: a cycle has at least two agents.

**The family** (`ringP`, `ringA`, `ringG`, `ringY`), with `N` leaves per tree (`N = 2^d` in the paper). The agent
`(i, p)` lies in component `i < k` at heap position `1 ≤ p < 2N` of a binary tree: `o_i = (i, 1)` is the root, the
inner agents are `p < N` with children `2p` and `2p + 1`, the leaves are `N ≤ p < 2N`. Every agent `(i, p)` holds one
good, `node i p`, alone; there are no pair holders. An agent with `p < N` (`o_i` or an inner agent) ranks
`node i (2p) ≻ node i (2p+1) ≻ node i p`: it holds its `c` and needs its children's goods. The leaf `(i, p)` ranks its
own good first (it holds its top and needs nothing), then `node (i−1) 1` (the good of `o_{i−1}`) and its label, in
this order if `p − N` is even and in the other order if it is odd. Labels: private (`lab i p`, one per leaf), or shared
(`pool j`, `j < k`; the leaf `(i, p)` gets `pool ((p − N) mod k)`).

**Results.**
- `wf`, `nodup_ringA`, `nodup_ringG`, `valid`, `propP`: a well-formed core instance; the state is valid
  (`EFX.LB.Valid`) and satisfies (P), so `D⁺` and the protecting goods are defined.
- `free_iff`, `nFree`: the free agents are exactly the `k` agents `o_i`.
- `needArc_iff`, `exposed_iff`, `expArc_iff`, `arc_cases`, `hOf_leaf`: the need arcs go from a child to its parent;
  the exposure arcs go from `o_{i−1}` to the leaves of tree `i`, labelled by the leaf's label.
- `no_free_absorber`, `not_completable` (`k ≤ N`); `free_absorber_of_lt` (`N < k`: `o_0` absorbs);
  `no_free_absorber_iff`: **no free agent is a valid absorber iff `k ≤ N`**.
- `countP_ring` (a lemma on closed walks), `nExp_eq`: **every cycle of `D⁺` uses exactly `k` exposure arcs**, for all
  `k ≥ 2` and `N ≥ 2`, with distinct labels or not, and without `k ≤ N`. Proof: a need arc stays in its component and
  lowers the position, an exposure arc out of `o_i` enters component `i + 1 mod k`; summing the components around the
  cycle gives `#exposure arcs = k · #(arcs out of o_{k−1})`, at most one arc leaves `o_{k−1}`, and summing the
  positions shows that some arc is an exposure arc. `nExp_eq_of_labels` is the paper's statement.
- `ringCycle`, `dcycle_ringCycle`, `labels_ringCycle`: if `k ≤ N`, a cycle with distinct labels exists (up each tree
  `j` from the leaf `(j, N + j)` to `o_j`, then to the next tree), so the statement is not vacuous.
- `gen_tree_ring`: all of this for `N = 2^d`, every `k ≥ 2` and `d ≥ 1` with `k ≤ 2^d`. The parameters the paper
  cites, `(k, d) ∈ {(2, 1), (3, 2), (4, 2), (5, 3)}`, are instances.

**Differences from the paper.** The paper's family is stated for the cited parameters; here `k`, `d` are arbitrary.
"No free agent absorbs" needs `k ≤ 2^d` (`o_i` has `2^d` exposed leaves, so `|H_{o_i}| = min(2^d, k)` with shared
labels and `2^d` with private ones); all cited parameters satisfy it. The paper says every cycle with distinct labels
uses `k` exposure arcs; every cycle does. Not formalized: that every Pareto improvement upgrades `k` agents (the paper
does not claim it either), and the identification with the Python generator (below).

**Choices where the prose leaves room.**
1. The heap layout. For `N = 2^d` it is `gen_tree(k, d, shared)` up to renaming: the generator's agent `i < k` is
   `o_i = (i, 1)`, its trees are built depth first with the left subtree first (the heap positions in order), its
   `s`-th leaf of the tree of `o_i` is `(i, N + s)`, its `own[i]` is `node i 1`, and its other goods are the `node`
   goods and the labels. The parity order of a leaf's `b` and `c` is the generator's. The definitions and proofs work
   for every `N ≥ 2` (a binary tree with `N` leaves, perfect when `N` is a power of two).
2. A cycle is a list (the paper's `(w_0, …, w_{k−1})`); exposure arcs are counted with the Boolean `expArcB`
   (`expArcB_iff`). Here no arc is both a need arc and an exposure arc (`arc_cases`).
3. The label of an exposure arc `o → x` is `EFX.DE.hOf x`, the one of `b x`, `c x` that is junk: the paper's `h_x`
   under (P) (`EFX.DE.forced_hOf`).
4. With shared labels and `N < k` the pool goods `pool j`, `j ≥ N`, are valued by nobody, as in the generator.
-/

set_option autoImplicit false

namespace EFX
namespace DE
namespace Rings

open LB Profile

/-! ## The exchange digraph `D⁺` and its cycles -/

section Dplus

variable {A G : Type} [DecidableEq A] [DecidableEq G]

/-- **A need arc** `j → j'` of the need digraph `D` (the paper's Definition need digraph): `j` and `j'` are listed agents
outside `up`, `j` holds a single good `y`, and `y` is a need of `j'` (`j'` ranks it above its pick). -/
def NeedArc (P : Profile A G) (agents up : List A) (Y : A → Option G) (j j' : A) : Prop :=
  j ∈ agents ∧ j ∉ up ∧ j' ∈ agents ∧ j' ∉ up ∧ ∃ y, Y j = some y ∧ P.Prefers Y j' y

/-- **An exposure arc** `o → x` (the paper's Definition exchange digraph): `o` is a free agent that holds a good, and `x`
is exposed for `o`. Its label is the protecting good `hOf x`. -/
def ExpArc (P : Profile A G) (agents up : List A) (Y : A → Option G) (goods : List G) (o x : A) : Prop :=
  Free P agents up Y o ∧ (∃ y, Y o = some y) ∧ Exposed P agents up Y goods o x

/-- An arc of the exchange digraph `D⁺`: a need arc or an exposure arc. -/
def Arc (P : Profile A G) (agents up : List A) (Y : A → Option G) (goods : List G) (u v : A) : Prop :=
  NeedArc P agents up Y u v ∨ ExpArc P agents up Y goods u v

/-- `ExpArc`, as a Boolean. -/
def expArcB (P : Profile A G) (agents up : List A) (Y : A → Option G) (goods : List G) (o x : A) : Bool :=
  freeB P agents up Y o && (Y o).isSome && expB P agents up Y goods o x

theorem expArcB_iff {P : Profile A G} {agents up : List A} {Y : A → Option G} {goods : List G} {o x : A} :
    expArcB P agents up Y goods o x = true ↔ ExpArc P agents up Y goods o x := by
  simp [expArcB, ExpArc, freeB_iff, expB_iff, Option.isSome_iff_exists, and_assoc]

end Dplus

/-- The consecutive pairs of a list. -/
def steps {α : Type} : List α → List (α × α)
  | u :: v :: l => (u, v) :: steps (v :: l)
  | _ => []

/-- The arcs of the closed walk through `c`: each agent to the next, and the last to the first. -/
def cycArcs {α : Type} (c : List α) : List (α × α) := steps (c ++ c.take 1)

section Dplus

variable {A G : Type} [DecidableEq A] [DecidableEq G]

/-- **A cycle of `D⁺`**: a nonempty list of distinct agents, each joined to the next, and the last to the first, by an
arc of `D⁺`. -/
structure DCycle (P : Profile A G) (agents up : List A) (Y : A → Option G) (goods : List G) (c : List A) : Prop where
  ne : c ≠ []
  nodup : c.Nodup
  arc : ∀ e ∈ cycArcs c, Arc P agents up Y goods e.1 e.2

/-- The number of exposure arcs of the cycle `c`. -/
def nExp (P : Profile A G) (agents up : List A) (Y : A → Option G) (goods : List G) (c : List A) : Nat :=
  (cycArcs c).countP (fun e => expArcB P agents up Y goods e.1 e.2)

/-- The labels of the exposure arcs of the cycle `c`, in order: the protecting goods of their heads. The cycle has
*distinct labels* if this list has no repetition. -/
def labels (P : Profile A G) (agents up : List A) (Y : A → Option G) (goods : List G) (c : List A) : List G :=
  ((cycArcs c).filter (fun e => expArcB P agents up Y goods e.1 e.2)).map (fun e => hOf P agents up Y goods e.2)

omit [DecidableEq A] in
/-- `D⁺` has no loops: an agent does not need its own good, and is not exposed for itself. -/
theorem arc_irrefl {P : Profile A G} {agents up : List A} {Y : A → Option G} {goods : List G} {w : A} :
    ¬ Arc P agents up Y goods w w := by
  rintro (⟨-, -, -, -, y, hy, hp⟩ | ⟨-, -, hE⟩)
  · simp [Profile.Prefers, Profile.pickRank, hy] at hp
  · exact hE.2.1 rfl

omit [DecidableEq A] in
/-- A cycle of `D⁺` has at least two agents (the paper's `k ≥ 2` in Definition exchange along a cycle). -/
theorem DCycle.two_le {P : Profile A G} {agents up : List A} {Y : A → Option G} {goods : List G} {c : List A}
    (hc : DCycle P agents up Y goods c) : 2 ≤ c.length := by
  match c, hc with
  | [], hc => exact absurd rfl hc.ne
  | [w], hc => exact absurd (hc.arc (w, w) (by simp [cycArcs, steps])) arc_irrefl
  | _ :: _ :: _, _ => simp

end Dplus

/-! ## Closed walks: telescoping and counting -/

section Walks

variable {α : Type}

theorem steps_cons_cons (u v : α) (l : List α) : steps (u :: v :: l) = (u, v) :: steps (v :: l) := rfl

theorem steps_fst : ∀ l : List α, (steps l).map Prod.fst = l.dropLast
  | [] => rfl
  | [_] => rfl
  | u :: v :: l => by
    rw [steps_cons_cons, List.map_cons, steps_fst (v :: l)]
    rfl

theorem steps_snd : ∀ l : List α, (steps l).map Prod.snd = l.tail
  | [] => rfl
  | [_] => rfl
  | u :: v :: l => by
    rw [steps_cons_cons, List.map_cons, steps_snd (v :: l)]
    rfl

theorem cycArcs_fst (u : α) (c : List α) : (cycArcs (u :: c)).map Prod.fst = u :: c := by
  unfold cycArcs
  rw [steps_fst]
  simp only [List.take_succ_cons, List.take_zero, List.cons_append]
  rw [List.dropLast_cons_of_ne_nil (by simp), List.dropLast_concat]

theorem cycArcs_snd (u : α) (c : List α) : (cycArcs (u :: c)).map Prod.snd = c ++ [u] := by
  unfold cycArcs
  rw [steps_snd]
  simp

theorem length_cycArcs (c : List α) : (cycArcs c).length = c.length := by
  cases c with
  | nil => rfl
  | cons u c =>
    have := congrArg List.length (cycArcs_fst u c)
    simpa using this

theorem sum_cyc_fst (f : α → Nat) (c : List α) : ((cycArcs c).map (fun e => f e.1)).sum = (c.map f).sum := by
  cases c with
  | nil => rfl
  | cons u c =>
    have := congrArg (fun l => (l.map f).sum) (cycArcs_fst u c)
    simpa [List.map_map, Function.comp_def] using this

theorem sum_cyc_snd (f : α → Nat) (c : List α) : ((cycArcs c).map (fun e => f e.2)).sum = (c.map f).sum := by
  cases c with
  | nil => rfl
  | cons u c =>
    have := congrArg (fun l => (l.map f).sum) (cycArcs_snd u c)
    simp only [List.map_map, Function.comp_def, List.map_append, List.sum_append, List.map_cons, List.map_nil,
      List.sum_cons, List.sum_nil] at this
    rw [this]
    simp only [List.map_cons, List.sum_cons]
    omega

/-- In a duplicate-free closed walk, at most one arc leaves a given vertex. -/
theorem countP_tail_le [DecidableEq α] {c : List α} (hnd : c.Nodup) (t : α) :
    (cycArcs c).countP (fun e => e.1 == t) ≤ 1 := by
  cases c with
  | nil => simp [cycArcs, steps]
  | cons u c =>
    have h := List.countP_map (p := fun x => x == t) (f := Prod.fst) (l := cycArcs (u :: c))
    rw [cycArcs_fst] at h
    have h1 := (List.nodup_iff_count.mp hnd) t
    rw [List.count_eq_countP] at h1
    have h2 : (cycArcs (u :: c)).countP (fun e => e.1 == t) =
        (cycArcs (u :: c)).countP ((fun x => x == t) ∘ Prod.fst) := rfl
    omega

theorem sum_add_eq {β : Type} {L : List β} {F G H K : β → Nat} (h : ∀ e ∈ L, F e + G e = H e + K e) :
    (L.map F).sum + (L.map G).sum = (L.map H).sum + (L.map K).sum := by
  induction L with
  | nil => simp
  | cons e L ih =>
    simp only [List.map_cons, List.sum_cons]
    have h1 := h e List.mem_cons_self
    have h2 := ih (fun e' he' => h e' (List.mem_cons_of_mem _ he'))
    omega

theorem sum_succ_le {β : Type} {L : List β} {F H : β → Nat} (h : ∀ e ∈ L, F e + 1 ≤ H e) :
    (L.map F).sum + L.length ≤ (L.map H).sum := by
  induction L with
  | nil => simp
  | cons e L ih =>
    simp only [List.map_cons, List.sum_cons, List.length_cons]
    have h1 := h e List.mem_cons_self
    have h2 := ih (fun e' he' => h e' (List.mem_cons_of_mem _ he'))
    omega

theorem sum_ite_countP {β : Type} (L : List β) (p : β → Bool) (m : Nat) :
    (L.map (fun e => if p e then m else 0)).sum = m * L.countP p := by
  induction L with
  | nil => simp
  | cons e L ih =>
    simp only [List.map_cons, List.sum_cons, List.countP_cons, ih]
    cases p e <;> simp [Nat.mul_add] <;> omega

/-- **Counting the arcs that go around a ring.** Let `c` be a duplicate-free nonempty closed walk whose vertices have
a component `comp` and a height `pos`, and whose arcs are of two kinds (`isE`). An arc that is not of the second kind
stays in its component and goes down; an arc of the second kind goes to the next component (`comp + 1`), except the
arcs leaving `last`, which are of the second kind and go from component `k - 1` to component `0`. Then exactly `k` arcs
of `c` are of the second kind. (The components add up to `0` around the walk, so `#isE = k · #(arcs leaving last)`;
at most one arc leaves `last`; and since the heights add up to `0`, some arc is of the second kind.) -/
theorem countP_ring {β : Type} [DecidableEq β] (k : Nat) (comp pos : β → Nat) (isE : β → β → Bool) (last : β)
    {c : List β} (hne : c ≠ []) (hnd : c.Nodup)
    (hlast : ∀ e ∈ cycArcs c, e.1 = last → isE e.1 e.2 = true ∧ comp e.2 + k = comp e.1 + 1)
    (hexp : ∀ e ∈ cycArcs c, e.1 ≠ last → isE e.1 e.2 = true → comp e.2 = comp e.1 + 1)
    (hneed : ∀ e ∈ cycArcs c, isE e.1 e.2 = false → comp e.2 = comp e.1 ∧ pos e.2 < pos e.1) :
    (cycArcs c).countP (fun e => isE e.1 e.2) = k := by
  have hW := countP_tail_le hnd last
  have hbal := sum_add_eq (L := cycArcs c) (F := fun e => comp e.2) (G := fun e => if e.1 == last then k else 0)
    (H := fun e => comp e.1) (K := fun e => if isE e.1 e.2 then 1 else 0) (fun e he => by
      by_cases h1 : e.1 = last
      · obtain ⟨h2, h3⟩ := hlast e he h1
        rw [ite_eq_left (by simp [h1]), ite_eq_left h2]
        omega
      · cases h2 : isE e.1 e.2
        · have := hneed e he h2
          rw [ite_eq_right (by simp [h1]), ite_eq_right (by simp)]
          omega
        · have := hexp e he h1 h2
          rw [ite_eq_right (by simp [h1]), ite_eq_left rfl]
          omega)
  have e1 : ((cycArcs c).map (fun e => if (e.1 == last) = true then k else 0)).sum =
      k * (cycArcs c).countP (fun e => e.1 == last) := sum_ite_countP _ _ _
  have e2 : ((cycArcs c).map (fun e => if isE e.1 e.2 = true then 1 else 0)).sum =
      1 * (cycArcs c).countP (fun e => isE e.1 e.2) := sum_ite_countP _ _ _
  rw [sum_cyc_fst, sum_cyc_snd, e1, e2, Nat.one_mul] at hbal
  have hE1 : 1 ≤ (cycArcs c).countP (fun e => isE e.1 e.2) := by
    refine Nat.pos_of_ne_zero fun h0 => ?_
    have hall := List.countP_eq_zero.mp h0
    have hs := sum_succ_le (L := cycArcs c) (F := fun e => pos e.2) (H := fun e => pos e.1) (fun e he => by
      have := hneed e he (by simpa using hall e he)
      omega)
    rw [sum_cyc_fst, sum_cyc_snd, length_cycArcs] at hs
    have : 0 < c.length := List.length_pos_iff.mpr hne
    omega
  have h01 : (cycArcs c).countP (fun e => e.1 == last) = 0 ∨ (cycArcs c).countP (fun e => e.1 == last) = 1 := by
    omega
  rcases h01 with h | h
  · rw [h, Nat.mul_zero] at hbal
    omega
  · rw [h, Nat.mul_one] at hbal
    omega

end Walks

/-! ## The ring family -/

/-- The goods of the ring family: `node i p` is the good held by the agent `(i, p)`; `lab i p` is the private label of
the leaf `(i, p)`; `pool j` is the `j`-th good of the shared pool. -/
inductive Good where
  | node (i p : Nat)
  | lab (i p : Nat)
  | pool (j : Nat)
  deriving DecidableEq

/-- An agent `(i, p)`: the component `i < k` and the heap position `1 ≤ p < 2N` in the tree of component `i`
(position `1` is the free agent `o_i`, the children of `p` are `2p` and `2p + 1`, the leaves are `N ≤ p < 2N`). -/
abbrev Agent := Nat × Nat

/-- The previous component on the ring. -/
def prev (k i : Nat) : Nat := if i = 0 then k - 1 else i - 1

/-- The label (protecting good) of the leaf `x`: private (`lab`), or the shared good `pool ((x.2 − N) mod k)`. -/
def label (k N : Nat) (sh : Bool) (x : Agent) : Good :=
  if sh then .pool ((x.2 - N) % k) else .lab x.1 x.2

/-- **The rankings** (`gen_tree(k, d, shared)` with `N = 2^d`). An agent `(i, p)` with `p < N` (the free agent `o_i`
for `p = 1`, an inner node of its tree otherwise) ranks the goods of its children first and its own good last:
`node i (2p) ≻ node i (2p+1) ≻ node i p`. The leaf `(i, p)`, `p ≥ N`, ranks its own good first, then the good
`node (i−1) 1` of `o_{i−1}` and its label, in this order if `p − N` is even and in the other order if it is odd. -/
def ringP (k N : Nat) (sh : Bool) : Profile Agent Good where
  a x := if x.2 < N then .node x.1 (2 * x.2) else .node x.1 x.2
  b x := if x.2 < N then .node x.1 (2 * x.2 + 1)
    else if (x.2 - N) % 2 = 0 then .node (prev k x.1) 1 else label k N sh x
  c x := if x.2 < N then .node x.1 x.2
    else if (x.2 - N) % 2 = 0 then label k N sh x else .node (prev k x.1) 1

/-- The agents: `(i, p)` with `i < k` and `1 ≤ p < 2N`. -/
def ringA (k N : Nat) : List Agent :=
  (List.range k).flatMap fun i => (List.range (2 * N - 1)).map fun q => (i, q + 1)

/-- The goods: one `node` good per agent, and the labels (private: one per leaf; shared: a pool of `k`). -/
def ringG (k N : Nat) (sh : Bool) : List Good :=
  (ringA k N).map (fun x => Good.node x.1 x.2) ++
    (if sh then (List.range k).map Good.pool
     else ((ringA k N).filter (fun x => decide (N ≤ x.2))).map (fun x => Good.lab x.1 x.2))

/-- **The state**: every agent `(i, p)` holds its good `node i p` alone (its `c` if `p < N`, its top if `p ≥ N`);
there are no pair holders (`up = []`). -/
def ringY (k N : Nat) (x : Agent) : Option Good :=
  if x.1 < k ∧ 1 ≤ x.2 ∧ x.2 < 2 * N then some (.node x.1 x.2) else none

variable {k N : Nat} {sh : Bool}

theorem mem_ringA {x : Agent} : x ∈ ringA k N ↔ x.1 < k ∧ 1 ≤ x.2 ∧ x.2 < 2 * N := by
  obtain ⟨i, p⟩ := x
  simp only [ringA, List.mem_flatMap, List.mem_range, List.mem_map, Prod.mk.injEq]
  constructor
  · rintro ⟨i', hi', q, hq, rfl, rfl⟩
    omega
  · rintro ⟨h1, h2, h3⟩
    exact ⟨i, h1, p - 1, by omega, rfl, by omega⟩

theorem nodup_ringA : (ringA k N).Nodup := by
  rw [List.nodup_iff_pairwise_ne, ringA, List.pairwise_flatMap]
  refine ⟨fun i _ => ?_, ?_⟩
  · rw [List.pairwise_map]
    exact List.pairwise_lt_range.imp (fun h e => by simp at e; omega)
  · exact List.pairwise_lt_range.imp (fun h x hx y hy e => by
      simp only [List.mem_map] at hx hy
      obtain ⟨q, -, rfl⟩ := hx
      obtain ⟨q', -, rfl⟩ := hy
      simp at e
      omega)

theorem ringY_of_mem {x : Agent} (hx : x ∈ ringA k N) : ringY k N x = some (.node x.1 x.2) := by
  simp [ringY, mem_ringA.mp hx]

theorem ringY_eq_some {x : Agent} {g : Good} : ringY k N x = some g ↔ x ∈ ringA k N ∧ g = .node x.1 x.2 := by
  rw [mem_ringA]
  by_cases h : x.1 < k ∧ 1 ≤ x.2 ∧ x.2 < 2 * N
  · simp [ringY, h, eq_comm]
  · simp [ringY, h]

theorem node_mem {i p : Nat} (h : (i, p) ∈ ringA k N) : Good.node i p ∈ ringG k N sh :=
  List.mem_append_left _ (List.mem_map.mpr ⟨(i, p), h, rfl⟩)

theorem label_mem (hk : 1 ≤ k) {x : Agent} (hx : x ∈ ringA k N) (hl : N ≤ x.2) : label k N sh x ∈ ringG k N sh := by
  apply List.mem_append_right
  cases sh with
  | true => exact List.mem_map.mpr ⟨_, List.mem_range.mpr (Nat.mod_lt _ (by omega)), rfl⟩
  | false => exact List.mem_map.mpr ⟨x, List.mem_filter.mpr ⟨hx, by simp [hl]⟩, rfl⟩

theorem label_ne_node {x : Agent} {i p : Nat} : label k N sh x ≠ .node i p := by
  cases sh <;> simp [label]

theorem prev_lt (hk : 1 ≤ k) {i : Nat} (hi : i < k) : prev k i < k := by
  unfold prev; split <;> omega

theorem prev_mem (hk : 1 ≤ k) (hN : 1 ≤ N) {i : Nat} (hi : i < k) : (prev k i, 1) ∈ ringA k N :=
  mem_ringA.mpr ⟨prev_lt hk hi, Nat.le_refl 1, by omega⟩

theorem a_int {x : Agent} (h : x.2 < N) : (ringP k N sh).a x = .node x.1 (2 * x.2) := by simp [ringP, h]
theorem b_int {x : Agent} (h : x.2 < N) : (ringP k N sh).b x = .node x.1 (2 * x.2 + 1) := by simp [ringP, h]
theorem c_int {x : Agent} (h : x.2 < N) : (ringP k N sh).c x = .node x.1 x.2 := by simp [ringP, h]
theorem a_leaf {x : Agent} (h : N ≤ x.2) : (ringP k N sh).a x = .node x.1 x.2 := by
  simp [ringP, Nat.not_lt.mpr h]

theorem bc_leaf {x : Agent} (h : N ≤ x.2) :
    ((ringP k N sh).b x = .node (prev k x.1) 1 ∧ (ringP k N sh).c x = label k N sh x) ∨
      ((ringP k N sh).b x = label k N sh x ∧ (ringP k N sh).c x = .node (prev k x.1) 1) := by
  by_cases hp : (x.2 - N) % 2 = 0
  · left; simp [ringP, Nat.not_lt.mpr h, hp]
  · right; simp [ringP, Nat.not_lt.mpr h, hp]

theorem rank_lt_three {A G : Type} [DecidableEq G] {P : Profile A G} {i : A} {g : G}
    (h : g = P.a i ∨ g = P.b i ∨ g = P.c i) : P.rank i g < 3 := by
  unfold Profile.rank
  split
  · omega
  · split
    · omega
    · split
      · omega
      · exfalso
        rcases h with h | h | h <;> contradiction

/-- The needs of an agent: an inner agent `(i, p)` needs the goods of its two children; a leaf needs nothing. -/
theorem prefers_iff {x : Agent} (hx : x ∈ ringA k N) {g : Good} :
    (ringP k N sh).Prefers (ringY k N) x g ↔ x.2 < N ∧ (g = .node x.1 (2 * x.2) ∨ g = .node x.1 (2 * x.2 + 1)) := by
  have h1 := (mem_ringA.mp hx).2.1
  unfold Profile.Prefers Profile.pickRank
  rw [ringY_of_mem hx]
  dsimp only
  by_cases hp : x.2 < N
  · have hr : (ringP k N sh).rank x (.node x.1 x.2) = 2 := by
      unfold Profile.rank
      rw [a_int hp, b_int hp, c_int hp, ite_eq_right (by simp; omega), ite_eq_right (by simp; omega),
        ite_eq_left rfl]
    rw [hr]
    unfold Profile.rank
    rw [a_int hp, b_int hp, c_int hp]
    by_cases ha : g = .node x.1 (2 * x.2)
    · simp [ha, hp]
    · by_cases hb : g = .node x.1 (2 * x.2 + 1)
      · rw [ite_eq_right ha, ite_eq_left hb]
        simp [hb, hp]
      · rw [ite_eq_right ha, ite_eq_right hb]
        simp only [ha, hb, or_self, and_false, iff_false]
        split <;> omega
  · have hr : (ringP k N sh).rank x (.node x.1 x.2) = 0 := by
      unfold Profile.rank
      rw [a_leaf (Nat.not_lt.mp hp), ite_eq_left rfl]
    rw [hr]
    simp [hp]

theorem na_iff {g : Good} : (ringP k N sh).NA (ringA k N) (· ∈ ([] : List Agent)) (ringY k N) g ↔
    ∃ x ∈ ringA k N, x.2 < N ∧ (g = .node x.1 (2 * x.2) ∨ g = .node x.1 (2 * x.2 + 1)) := by
  unfold Profile.NA
  constructor
  · rintro ⟨x, hx, -, hp⟩
    exact ⟨x, hx, (prefers_iff hx).mp hp⟩
  · rintro ⟨x, hx, h⟩
    exact ⟨x, hx, by simp, (prefers_iff hx).mpr h⟩

/-- The needed goods are the goods of the agents other than the `o_i`. -/
theorem na_node {i p : Nat} (h : (i, p) ∈ ringA k N) (hp : 2 ≤ p) :
    (ringP k N sh).NA (ringA k N) (· ∈ ([] : List Agent)) (ringY k N) (.node i p) := by
  have h' := mem_ringA.mp h
  refine na_iff.mpr ⟨(i, p / 2), mem_ringA.mpr ⟨h'.1, by simp; omega, by simp; omega⟩, by simp; omega, ?_⟩
  simp only [Good.node.injEq, true_and]
  omega

theorem na_imp {g : Good} (h : (ringP k N sh).NA (ringA k N) (· ∈ ([] : List Agent)) (ringY k N) g) :
    ∃ x ∈ ringA k N, 2 ≤ x.2 ∧ g = .node x.1 x.2 := by
  obtain ⟨x, hx, hp, h | h⟩ := na_iff.mp h <;> have hx' := mem_ringA.mp hx
  · exact ⟨(x.1, 2 * x.2), mem_ringA.mpr ⟨hx'.1, by simp; omega, by simp; omega⟩, by simp; omega, h⟩
  · exact ⟨(x.1, 2 * x.2 + 1), mem_ringA.mpr ⟨hx'.1, by simp, by simp; omega⟩, by simp; omega, h⟩

/-- **The free agents** are the `k` agents `o_i = (i, 1)`. -/
theorem free_iff {x : Agent} : Free (ringP k N sh) (ringA k N) [] (ringY k N) x ↔ x ∈ ringA k N ∧ x.2 = 1 := by
  constructor
  · rintro ⟨hx, -, hf⟩
    refine ⟨hx, ?_⟩
    have hx' := mem_ringA.mp hx
    rcases Nat.lt_or_ge x.2 2 with h | h
    · omega
    · exact absurd (na_node hx h) (hf _ (ringY_of_mem hx))
  · rintro ⟨hx, h1⟩
    refine ⟨hx, by simp, fun y hy hna => ?_⟩
    rw [ringY_of_mem hx] at hy
    cases hy
    obtain ⟨z, -, h2, e⟩ := na_imp hna
    simp only [Good.node.injEq] at e
    omega

/-- **The state is valid** (the paper's Definition validity, `EFX.LB.Valid`): every needed good is the only good of
an agent. -/
theorem valid : Valid (ringP k N sh) (ringA k N) (ringG k N sh) (ringY k N) [] where
  pick := fun x y hy => by
    obtain ⟨hx, rfl⟩ := ringY_eq_some.mp hy
    refine ⟨hx, node_mem hx, rank_lt_three ?_⟩
    by_cases hp : x.2 < N
    · exact Or.inr (Or.inr (c_int hp).symm)
    · exact Or.inl (a_leaf (Nat.not_lt.mp hp)).symm
  pick_inj := fun x x' y hy hy' => by
    obtain ⟨-, rfl⟩ := ringY_eq_some.mp hy
    obtain ⟨-, e⟩ := ringY_eq_some.mp hy'
    simp only [Good.node.injEq] at e
    exact Prod.ext e.1 e.2
  up_mem := by simp
  up_b := by simp
  up_c := by simp
  up_c_inj := by simp
  v1 := fun g _ hp _ hna => by
    obtain ⟨x, hx, -, rfl⟩ := na_imp hna
    exact hp x (ringY_of_mem hx)
  v2 := by simp

/-- **The profile is well formed** (`EFX.LB.WF`): each agent ranks three distinct listed goods. -/
theorem wf (hk : 1 ≤ k) (hN : 2 ≤ N) : WF (ringP k N sh) (ringA k N) (ringG k N sh) := by
  intro x hx
  have hx' := mem_ringA.mp hx
  by_cases hp : x.2 < N
  · rw [a_int hp, b_int hp, c_int hp]
    refine ⟨node_mem (mem_ringA.mpr ⟨hx'.1, by omega, by omega⟩),
      node_mem (mem_ringA.mpr ⟨hx'.1, by omega, by omega⟩), node_mem hx, ?_, ?_, ?_⟩ <;>
      (simp only [ne_eq, Good.node.injEq, true_and]; omega)
  · have hl := Nat.not_lt.mp hp
    have hnm : Good.node (prev k x.1) 1 ∈ ringG k N sh := node_mem (prev_mem hk (by omega) hx'.1)
    have hne : Good.node x.1 x.2 ≠ .node (prev k x.1) 1 := by simp only [ne_eq, Good.node.injEq]; omega
    rw [a_leaf hl]
    rcases bc_leaf (sh := sh) hl with ⟨eb, ec⟩ | ⟨eb, ec⟩ <;> rw [eb, ec]
    · exact ⟨node_mem hx, hnm, label_mem hk hx hl, hne, label_ne_node.symm, label_ne_node.symm⟩
    · exact ⟨node_mem hx, label_mem hk hx hl, hnm, label_ne_node.symm, hne, label_ne_node⟩

/-- The goods are listed once each. -/
theorem nodup_ringG : (ringG k N sh).Nodup := by
  rw [ringG, List.nodup_append]
  refine ⟨?_, ?_, ?_⟩
  · rw [List.nodup_iff_pairwise_ne, List.pairwise_map]
    exact (List.nodup_iff_pairwise_ne.mp nodup_ringA).imp fun h e => by
      simp only [Good.node.injEq] at e
      exact h (Prod.ext e.1 e.2)
  · cases sh with
    | true =>
      rw [ite_eq_left rfl, List.nodup_iff_pairwise_ne, List.pairwise_map]
      exact List.pairwise_lt_range.imp fun h e => by simp at e; omega
    | false =>
      rw [ite_eq_right (by simp), List.nodup_iff_pairwise_ne, List.pairwise_map]
      exact ((List.nodup_iff_pairwise_ne.mp nodup_ringA).filter _).imp fun h e => by
        simp only [Good.lab.injEq] at e
        exact h (Prod.ext e.1 e.2)
  · intro a ha b hb e
    obtain ⟨x, -, rfl⟩ := List.mem_map.mp ha
    subst e
    cases sh <;> simp at hb

theorem not_junk_node {i p : Nat} (h : (i, p) ∈ ringA k N) :
    Good.node i p ∉ junkList (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) :=
  fun hj => ((junk_iff valid).mp hj).2.1 (i, p) (ringY_of_mem h)

theorem junk_label (hk : 1 ≤ k) {x : Agent} (hx : x ∈ ringA k N) (hl : N ≤ x.2) :
    label k N sh x ∈ junkList (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) :=
  (junk_iff valid).mpr ⟨label_mem hk hx hl, fun z hz => label_ne_node (ringY_eq_some.mp hz).2, by simp⟩

/-- **(P) holds**: no agent that holds only its top has its two other goods in the junk (the good of `o_{i−1}` is
held). So the protecting goods and `D⁺` are defined. -/
theorem propP (hk : 1 ≤ k) (hN : 2 ≤ N) : PropP (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) := by
  intro x hx _ hxa hj
  have hx' := mem_ringA.mp hx
  rw [ringY_of_mem hx] at hxa
  by_cases hp : x.2 < N
  · rw [a_int hp] at hxa
    simp only [Option.some.injEq, Good.node.injEq] at hxa
    omega
  · have hnj := not_junk_node (sh := sh) (prev_mem (N := N) hk (by omega) hx'.1)
    rcases bc_leaf (sh := sh) (Nat.not_lt.mp hp) with ⟨eb, -⟩ | ⟨-, ec⟩
    · exact hnj (eb ▸ hj.1)
    · exact hnj (ec ▸ hj.2)

/-- **Exposure**: `x` is exposed for `o` iff `x` is a leaf and `o = o_{i−1}`, where `i` is `x`'s component. -/
theorem exposed_iff (hk : 1 ≤ k) (hN : 2 ≤ N) {o x : Agent} :
    Exposed (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) o x ↔
      x ∈ ringA k N ∧ N ≤ x.2 ∧ o = (prev k x.1, 1) := by
  constructor
  · rintro ⟨hx, -, -, hxa, hb, hc⟩
    have hx' := mem_ringA.mp hx
    rw [ringY_of_mem hx] at hxa
    have hl : N ≤ x.2 := by
      refine Nat.not_lt.mp fun hp => ?_
      rw [a_int hp] at hxa
      simp only [Option.some.injEq, Good.node.injEq] at hxa
      omega
    have hnj := not_junk_node (sh := sh) (prev_mem (N := N) hk (by omega) hx'.1)
    have hbase : InBase (ringP k N sh) [] (ringY k N) o (.node (prev k x.1) 1) := by
      rcases bc_leaf (sh := sh) hl with ⟨eb, -⟩ | ⟨-, ec⟩
      · rw [eb] at hb; exact hb.resolve_left hnj
      · rw [ec] at hc; exact hc.resolve_left hnj
    rcases hbase with hY | ⟨hu, -⟩
    · obtain ⟨-, e⟩ := ringY_eq_some.mp hY
      simp only [Good.node.injEq] at e
      exact ⟨hx, hl, Prod.ext e.1.symm e.2.symm⟩
    · simp at hu
  · rintro ⟨hx, hl, rfl⟩
    have hx' := mem_ringA.mp hx
    have hbase : InBase (ringP k N sh) [] (ringY k N) (prev k x.1, 1) (.node (prev k x.1) 1) :=
      Or.inl (ringY_of_mem (prev_mem hk (by omega) hx'.1))
    have hj := junk_label (sh := sh) hk hx hl
    refine ⟨hx, fun e => by rw [e] at hl; simp at hl; omega, by simp, by rw [ringY_of_mem hx, a_leaf hl], ?_, ?_⟩ <;>
      rcases bc_leaf (sh := sh) hl with ⟨eb, ec⟩ | ⟨eb, ec⟩
    · rw [eb]; exact Or.inr hbase
    · rw [eb]; exact Or.inl hj
    · rw [ec]; exact Or.inl hj
    · rw [ec]; exact Or.inr hbase

/-- The protecting good of a leaf is its label. -/
theorem hOf_leaf (hk : 1 ≤ k) (hN : 2 ≤ N) {x : Agent} (hx : x ∈ ringA k N) (hl : N ≤ x.2) :
    hOf (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) x = label k N sh x := by
  have hnj := not_junk_node (sh := sh) (prev_mem (N := N) hk (by omega) (mem_ringA.mp hx).1)
  unfold hOf
  rcases bc_leaf (sh := sh) hl with ⟨eb, ec⟩ | ⟨eb, ec⟩ <;> rw [eb, ec]
  · have : junkB (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) (.node (prev k x.1) 1) = false := by
      cases h : junkB (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) (.node (prev k x.1) 1) with
      | false => rfl
      | true => exact absurd (junkB_iff.mp h) hnj
    simp [this]
  · simp [junkB_iff.mpr (junk_label hk hx hl)]

/-- **There are exactly `k` free agents.** -/
theorem nFree (hN : 1 ≤ N) :
    ((ringA k N).filter (freeB (ringP k N sh) (ringA k N) [] (ringY k N))).length = k := by
  have hmem : ∀ x, x ∈ (ringA k N).filter (freeB (ringP k N sh) (ringA k N) [] (ringY k N)) ↔
      x ∈ (List.range k).map (fun i => ((i, 1) : Agent)) := by
    intro x
    rw [List.mem_filter, freeB_iff, free_iff, List.mem_map, mem_ringA]
    constructor
    · rintro ⟨-, ⟨h1, -, -⟩, h2⟩
      exact ⟨x.1, List.mem_range.mpr h1, Prod.ext rfl h2.symm⟩
    · rintro ⟨i, hi, rfl⟩
      have hi' := List.mem_range.mp hi
      exact ⟨⟨hi', Nat.le_refl 1, by omega⟩, ⟨hi', Nat.le_refl 1, by omega⟩, rfl⟩
  have hnd1 := nodup_ringA (k := k) (N := N) |>.sublist (List.filter_sublist (p := freeB (ringP k N sh) (ringA k N) []
    (ringY k N)))
  have hnd2 : ((List.range k).map (fun i => ((i, 1) : Agent))).Nodup := by
    rw [List.nodup_iff_pairwise_ne, List.pairwise_map]
    exact List.pairwise_lt_range.imp fun h e => by simp at e; omega
  have h1 := length_le_of_nodup_of_subset hnd1 (fun x hx => (hmem x).mp hx)
  have h2 := length_le_of_nodup_of_subset hnd2 (fun x hx => (hmem x).mpr hx)
  simp only [List.length_map, List.length_range] at h1 h2
  omega

/-! ## No free agent absorbs (exactly when `k ≤ N`) -/

/-- A set `H` of junk goods that meets `{b x, c x}` for a leaf `x` contains the label of `x` (the other good of the
pair is held by `o_{i−1}`). -/
theorem label_of_hit (hk : 1 ≤ k) (hN : 2 ≤ N) {x : Agent} (hx : x ∈ ringA k N) (hl : N ≤ x.2) {H : List Good}
    (hH : ∀ h ∈ H, h ∈ junkList (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh))
    (hit : (ringP k N sh).b x ∈ H ∨ (ringP k N sh).c x ∈ H) : label k N sh x ∈ H := by
  have hnj := not_junk_node (sh := sh) (prev_mem (N := N) hk (by omega) (mem_ringA.mp hx).1)
  rcases bc_leaf (sh := sh) hl with ⟨eb, ec⟩ | ⟨eb, ec⟩ <;> rw [eb, ec] at hit
  · exact hit.resolve_left fun h => hnj (hH _ h)
  · exact hit.resolve_right fun h => hnj (hH _ h)

/-- The next component on the ring. -/
def next (k i : Nat) : Nat := if i + 1 = k then 0 else i + 1

theorem next_spec {i : Nat} (hi : i < k) : next k i < k ∧ prev k (next k i) = i := by
  by_cases h : i + 1 = k
  · simp [next, prev, h]; omega
  · simp [next, prev, h]; omega

/-- The labels of the leaves `(j, N + s)`, `s < k`, are `k` different goods. -/
theorem nodup_leafLabels (j : Nat) : ((List.range k).map (fun s => label k N sh (j, N + s))).Nodup := by
  rw [List.nodup_iff_pairwise_ne, List.pairwise_map]
  refine List.pairwise_lt_range.imp_of_mem (fun {s s'} hs hs' hlt e => ?_)
  have hs1 := List.mem_range.mp hs
  have hs2 := List.mem_range.mp hs'
  cases sh with
  | true =>
    simp only [label, ↓reduceIte, Good.pool.injEq, Nat.add_sub_cancel_left, Nat.mod_eq_of_lt hs1,
      Nat.mod_eq_of_lt hs2] at e
    omega
  | false =>
    simp only [label, Bool.false_eq_true, ↓reduceIte, Good.lab.injEq] at e
    omega

/-- **No free agent is a valid absorber** if `k ≤ N` (the paper's claim, for `N = 2^d`): the leaves of the next tree
are exposed for `o_i`, their labels are at least `k` protecting goods, and there are only `k − 1` other free agents. -/
theorem no_free_absorber (hk : 2 ≤ k) (hN : 2 ≤ N) (hkN : k ≤ N) :
    ¬ ∃ o H, Free (ringP k N sh) (ringA k N) [] (ringY k N) o ∧
      Absorber (ringP k N sh) (ringA k N) (ringG k N sh) (ringY k N) [] o H := by
  rintro ⟨o, H, hF, hA⟩
  obtain ⟨ho, ho1⟩ := free_iff.mp hF
  have ho' := mem_ringA.mp ho
  obtain ⟨hj, hpj⟩ := next_spec ho'.1
  have hsub : ∀ g ∈ (List.range k).map (fun s => label k N sh (next k o.1, N + s)), g ∈ H := by
    intro g hg
    obtain ⟨s, hs, rfl⟩ := List.mem_map.mp hg
    have hs' := List.mem_range.mp hs
    have hxa : (next k o.1, N + s) ∈ ringA k N := mem_ringA.mpr ⟨hj, by simp; omega, by simp; omega⟩
    have hE : Exposed (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) o (next k o.1, N + s) :=
      (exposed_iff (by omega) hN).mpr ⟨hxa, by simp, Prod.ext (by simp [hpj]) (by simp [ho1])⟩
    exact label_of_hit (by omega) hN hxa (by simp) hA.junk (hA.hit _ hE)
  have h1 := length_le_of_nodup_of_subset (nodup_leafLabels _) hsub
  have h2 := nFree_eq nodup_ringA hF
  rw [nFree (by omega)] at h2
  have h3 := hA.fit
  simp only [List.length_map, List.length_range] at h1
  omega

/-- **The state is not completable** if `k ≤ N`: no agent at all is a valid absorber (there are no pair holders). -/
theorem not_completable (hk : 2 ≤ k) (hN : 2 ≤ N) (hkN : k ≤ N) :
    ¬ ∃ o H, Absorber (ringP k N sh) (ringA k N) (ringG k N sh) (ringY k N) [] o H := by
  rintro ⟨o, H, hA⟩
  exact no_free_absorber hk hN hkN ⟨o, H, hA.ok.resolve_left (by simp), hA⟩

theorem length_dd_le {G : Type} [DecidableEq G] : ∀ l : List G, (dd l).length ≤ l.length
  | [] => by simp [dd]
  | x :: l => by
    have := length_dd_le l
    unfold dd
    split <;> simp <;> omega

/-- **If `N < k`, the free agent `o_0` is a valid absorber** (with `H = H_{o_0}`, at most `N` goods): the hypothesis
`k ≤ N` of `no_free_absorber` cannot be dropped. -/
theorem free_absorber_of_lt (hk : 2 ≤ k) (hN : 2 ≤ N) (hNk : N < k) :
    ∃ H, Absorber (ringP k N sh) (ringA k N) (ringG k N sh) (ringY k N) [] (0, 1) H := by
  have hF : Free (ringP k N sh) (ringA k N) [] (ringY k N) (0, 1) :=
    free_iff.mpr ⟨mem_ringA.mpr ⟨by simp; omega, by simp, by simp; omega⟩, rfl⟩
  refine ⟨_, absorber_forced (wf (by omega) hN) nodup_ringA (propP (by omega) hN) hF ?_⟩
  rw [nFree (by omega)]
  have hE : ∀ x ∈ (ringA k N).filter (expB (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) (0, 1)),
      x ∈ (List.range N).map (fun s => ((1, N + s) : Agent)) := by
    intro x hx
    obtain ⟨hxa, hxe⟩ := List.mem_filter.mp hx
    obtain ⟨-, hl, e⟩ := (exposed_iff (by omega) hN).mp (expB_iff.mp hxe)
    have hx' := mem_ringA.mp hxa
    have e1 := congrArg Prod.fst e
    simp only at e1
    have hx1 : x.1 = 1 := by
      unfold prev at e1
      split at e1 <;> omega
    exact List.mem_map.mpr ⟨x.2 - N, List.mem_range.mpr (by omega), Prod.ext (by simp [hx1]) (by simp; omega)⟩
  have hnd := (nodup_ringA (k := k) (N := N)).sublist
    (List.filter_sublist (p := expB (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) (0, 1)))
  have h1 := length_le_of_nodup_of_subset hnd hE
  have h2 := length_dd_le (((ringA k N).filter
    (expB (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) (0, 1))).map
    (hOf (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh)))
  simp only [List.length_map, List.length_range] at h1 h2
  unfold Hset
  omega

/-- **No free agent absorbs exactly when `k ≤ N`.** -/
theorem no_free_absorber_iff (hk : 2 ≤ k) (hN : 2 ≤ N) :
    (¬ ∃ o H, Free (ringP k N sh) (ringA k N) [] (ringY k N) o ∧
      Absorber (ringP k N sh) (ringA k N) (ringG k N sh) (ringY k N) [] o H) ↔ k ≤ N := by
  constructor
  · intro h
    refine Nat.not_lt.mp fun hlt => h ?_
    obtain ⟨H, hA⟩ := free_absorber_of_lt (sh := sh) hk hN hlt
    exact ⟨(0, 1), H, hA.ok.resolve_left (by simp), hA⟩
  · exact no_free_absorber hk hN

/-! ## The arcs of `D⁺`; every cycle uses exactly `k` exposure arcs -/

/-- **The need arcs** go from a child to its parent: `(i, p) → (i, ⌊p/2⌋)`. -/
theorem needArc_iff {u v : Agent} :
    NeedArc (ringP k N sh) (ringA k N) [] (ringY k N) u v ↔
      u ∈ ringA k N ∧ v ∈ ringA k N ∧ v.2 < N ∧ u.1 = v.1 ∧ (u.2 = 2 * v.2 ∨ u.2 = 2 * v.2 + 1) := by
  constructor
  · rintro ⟨hu, -, hv, -, y, hy, hp⟩
    obtain ⟨-, rfl⟩ := ringY_eq_some.mp hy
    obtain ⟨h1, h2⟩ := (prefers_iff hv).mp hp
    simp only [Good.node.injEq] at h2
    refine ⟨hu, hv, h1, ?_, ?_⟩ <;> omega
  · rintro ⟨hu, hv, h1, h2, h3⟩
    refine ⟨hu, by simp, hv, by simp, _, ringY_of_mem hu, (prefers_iff hv).mpr ⟨h1, ?_⟩⟩
    simp only [Good.node.injEq]
    omega

/-- **The exposure arcs** go from `o_{i−1} = (i − 1, 1)` to the leaves of the tree of component `i`. -/
theorem expArc_iff (hk : 1 ≤ k) (hN : 2 ≤ N) {o x : Agent} :
    ExpArc (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) o x ↔
      x ∈ ringA k N ∧ N ≤ x.2 ∧ o = (prev k x.1, 1) := by
  constructor
  · rintro ⟨-, -, hE⟩
    exact (exposed_iff hk hN).mp hE
  · rintro ⟨hx, hl, rfl⟩
    have hpm := prev_mem (N := N) hk (by omega) (mem_ringA.mp hx).1
    exact ⟨free_iff.mpr ⟨hpm, rfl⟩, ⟨_, ringY_of_mem hpm⟩, (exposed_iff hk hN).mpr ⟨hx, hl, rfl⟩⟩

/-- The two kinds of arcs of `D⁺`: a need arc stays in its component and goes up the tree (to a smaller position);
an exposure arc goes from `o_{i−1}` to a leaf of component `i`. -/
theorem arc_cases (hk : 1 ≤ k) (hN : 2 ≤ N) {u v : Agent}
    (h : Arc (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) u v) :
    (expArcB (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) u v = false ∧ v ∈ ringA k N ∧
        v.1 = u.1 ∧ v.2 < u.2) ∨
      (expArcB (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) u v = true ∧ v ∈ ringA k N ∧
        N ≤ v.2 ∧ u = (prev k v.1, 1)) := by
  rcases h with h | h
  · obtain ⟨-, hv, h1, h2, h3⟩ := needArc_iff.mp h
    have hv' := mem_ringA.mp hv
    refine Or.inl ⟨?_, hv, h2.symm, by omega⟩
    cases hb : expArcB (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) u v with
    | false => rfl
    | true =>
      obtain ⟨-, h4, -⟩ := (expArc_iff hk hN).mp (expArcB_iff.mp hb)
      omega
  · exact Or.inr ⟨expArcB_iff.mpr h, (expArc_iff hk hN).mp h⟩

/-- **Every cycle of `D⁺` uses exactly `k` exposure arcs**, for all `k ≥ 2` and `N ≥ 2`: all cycles, not only those
with distinct labels, and without the hypothesis `k ≤ N`. -/
theorem nExp_eq (hk : 2 ≤ k) (hN : 2 ≤ N) {c : List Agent}
    (hc : DCycle (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) c) :
    nExp (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) c = k := by
  have hk1 : 1 ≤ k := by omega
  refine countP_ring k Prod.fst Prod.snd (expArcB (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh))
    (k - 1, 1) hc.ne hc.nodup ?_ ?_ ?_
  · intro e he h1
    rcases arc_cases hk1 hN (hc.arc e he) with ⟨-, hv, -, hlt⟩ | ⟨hE, hv, -, hu⟩
    · have := (mem_ringA.mp hv).2.1
      rw [h1] at hlt
      simp only at hlt
      omega
    · refine ⟨hE, ?_⟩
      have hv' := (mem_ringA.mp hv).1
      rw [h1] at hu ⊢
      have e1 := congrArg Prod.fst hu
      simp only at e1 ⊢
      unfold prev at e1
      split at e1 <;> omega
  · intro e he h1 hE
    rcases arc_cases hk1 hN (hc.arc e he) with ⟨hE', -⟩ | ⟨-, hv, -, hu⟩
    · rw [hE] at hE'
      cases hE'
    · have hv' := (mem_ringA.mp hv).1
      rw [hu] at h1 ⊢
      have hne : prev k e.2.1 ≠ k - 1 := fun h => h1 (by rw [h])
      simp only
      by_cases h0 : e.2.1 = 0
      · simp [prev, h0] at hne
      · simp only [prev, h0, ↓reduceIte] at hne ⊢
        omega
  · intro e he hE
    rcases arc_cases hk1 hN (hc.arc e he) with ⟨-, -, h1, h2⟩ | ⟨hE', -⟩
    · exact ⟨h1, h2⟩
    · rw [hE] at hE'
      cases hE'

/-- The cycles with distinct labels in particular (the paper's statement). -/
theorem nExp_eq_of_labels (hk : 2 ≤ k) (hN : 2 ≤ N) {c : List Agent}
    (hc : DCycle (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) c)
    (_ : (labels (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) c).Nodup) :
    nExp (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) c = k :=
  nExp_eq hk hN hc

/-! ## A cycle of `D⁺` with distinct labels (the statement is not vacuous) -/

/-- The path up the tree of component `i` from position `p` to the root `(i, 1)`: `p, ⌊p/2⌋, ⌊p/4⌋, …, 1` (`f` is
fuel; `f = p` suffices). -/
def upPath (i : Nat) : Nat → Nat → List Agent
  | _, 0 => [(i, 1)]
  | p, f + 1 => if p ≤ 1 then [(i, 1)] else (i, p) :: upPath i (p / 2) f

/-- Components `i, i + 1, …, i + r − 1` of the ring cycle: in each component `j`, the path up its tree from the leaf
`(j, N + j)` to `o_j = (j, 1)`. -/
def ringPath (N : Nat) : Nat → Nat → List Agent
  | _, 0 => []
  | i, r + 1 => upPath i (N + i) (N + i) ++ ringPath N (i + 1) r

/-- **The ring cycle**: up the tree of component `0` from the leaf `(0, N)` to `o_0`, by an exposure arc to the leaf
`(1, N + 1)`, up to `o_1`, …, up to `o_{k−1}`, and by an exposure arc back to `(0, N)`. -/
def ringCycle (k N : Nat) : List Agent := ringPath N 0 k

theorem upPath_head {i : Nat} : ∀ {p f : Nat}, 1 ≤ p → p ≤ f → ∃ l, upPath i p f = (i, p) :: l
  | _, 0, h1, h2 => by omega
  | p, f + 1, h1, _ => by
    simp only [upPath]
    split
    · have : p = 1 := by omega
      subst this
      exact ⟨[], rfl⟩
    · exact ⟨_, rfl⟩

theorem upPath_last (i : Nat) : ∀ (p f : Nat), ∃ l, upPath i p f = l ++ [(i, 1)]
  | _, 0 => ⟨[], rfl⟩
  | p, f + 1 => by
    simp only [upPath]
    split
    · exact ⟨[], rfl⟩
    · obtain ⟨l, hl⟩ := upPath_last i (p / 2) f
      exact ⟨(i, p) :: l, by rw [hl]; rfl⟩

theorem mem_upPath {i : Nat} : ∀ {p f : Nat} {x : Agent}, x ∈ upPath i p f →
    x.1 = i ∧ 1 ≤ x.2 ∧ (x.2 = p ∨ 2 * x.2 ≤ p ∨ x.2 = 1)
  | _, 0, x, h => by
    simp only [upPath, List.mem_singleton] at h
    subst h
    simp
  | p, f + 1, x, h => by
    simp only [upPath] at h
    split at h
    · simp only [List.mem_singleton] at h
      subst h
      simp
    · rcases List.mem_cons.mp h with rfl | h
      · exact ⟨rfl, by simp only; omega, Or.inl rfl⟩
      · obtain ⟨h1, h2, h3⟩ := mem_upPath h
        exact ⟨h1, h2, by omega⟩

theorem nodup_upPath {i : Nat} : ∀ {p f : Nat}, (upPath i p f).Nodup
  | _, 0 => by simp [upPath]
  | p, f + 1 => by
    simp only [upPath]
    split
    · simp
    · refine List.nodup_cons.mpr ⟨fun h => ?_, nodup_upPath⟩
      obtain ⟨-, -, h3⟩ := mem_upPath h
      simp only at h3
      omega

theorem steps_append_cons {α : Type} (x y : α) (l2 : List α) : ∀ l : List α,
    steps (l ++ x :: y :: l2) = steps (l ++ [x]) ++ (x, y) :: steps (y :: l2)
  | [] => rfl
  | [_] => rfl
  | a :: b :: l => by
    have ih := steps_append_cons x y l2 (b :: l)
    simp only [List.cons_append] at ih ⊢
    rw [steps_cons_cons, steps_cons_cons, ih]
    rfl

theorem walk_join {α : Type} {R : α → α → Prop} {l l2 : List α} {x y : α}
    (h1 : ∀ e ∈ steps (l ++ [x]), R e.1 e.2) (h2 : R x y) (h3 : ∀ e ∈ steps (y :: l2), R e.1 e.2) :
    ∀ e ∈ steps (l ++ x :: y :: l2), R e.1 e.2 := by
  intro e he
  rw [steps_append_cons] at he
  rcases List.mem_append.mp he with h | h
  · exact h1 e h
  · rcases List.mem_cons.mp h with rfl | h
    · exact h2
    · exact h3 e h

/-- The path up a tree follows need arcs. -/
theorem walk_upPath {i : Nat} (hi : i < k) : ∀ {p f : Nat}, 1 ≤ p → p < 2 * N → p ≤ f →
    ∀ e ∈ steps (upPath i p f), NeedArc (ringP k N sh) (ringA k N) [] (ringY k N) e.1 e.2
  | _, 0, _, _, _ => by simp [upPath, steps]
  | p, f + 1, h1, h2, h3 => by
    simp only [upPath]
    split
    · simp [steps]
    · obtain ⟨l, hl⟩ := upPath_head (i := i) (p := p / 2) (f := f) (by omega) (by omega)
      have ih := walk_upPath hi (p := p / 2) (f := f) (by omega) (by omega) (by omega)
      rw [hl] at ih
      rw [hl, steps_cons_cons]
      intro e he
      rcases List.mem_cons.mp he with rfl | he
      · refine needArc_iff.mpr ⟨mem_ringA.mpr ⟨hi, by omega, by omega⟩, mem_ringA.mpr ⟨hi, ?_, ?_⟩, ?_, rfl, ?_⟩ <;>
          (simp only; omega)
      · exact ih e he

theorem mem_ringPath {N : Nat} : ∀ {i r : Nat} {x : Agent}, x ∈ ringPath N i r →
    i ≤ x.1 ∧ x.1 < i + r ∧ x ∈ upPath x.1 (N + x.1) (N + x.1)
  | _, 0, _, h => by simp [ringPath] at h
  | i, r + 1, x, h => by
    simp only [ringPath, List.mem_append] at h
    rcases h with h | h
    · obtain ⟨h1, -⟩ := mem_upPath h
      refine ⟨by omega, by omega, ?_⟩
      rw [h1]
      exact h
    · obtain ⟨h1, h2, h3⟩ := mem_ringPath h
      exact ⟨by omega, by omega, h3⟩

theorem nodup_ringPath {N : Nat} : ∀ {i r : Nat}, (ringPath N i r).Nodup
  | _, 0 => by simp [ringPath]
  | i, r + 1 => by
    simp only [ringPath]
    refine List.nodup_append.mpr ⟨nodup_upPath, nodup_ringPath, fun a ha b hb e => ?_⟩
    have h1 := (mem_upPath ha).1
    have h2 := (mem_ringPath hb).1
    subst e
    omega

theorem ringPath_head {N : Nat} (hN : 1 ≤ N) {i r : Nat} (hr : 1 ≤ r) : ∃ l, ringPath N i r = (i, N + i) :: l := by
  cases r with
  | zero => omega
  | succ r =>
    obtain ⟨l, hl⟩ := upPath_head (i := i) (p := N + i) (f := N + i) (by omega) (Nat.le_refl _)
    exact ⟨l ++ ringPath N (i + 1) r, by simp only [ringPath, hl, List.cons_append]⟩

/-- The exposure arc from `o_i` to the leaf `(i + 1, N + i + 1)`. -/
theorem arc_next (hk : 1 ≤ k) (hN : 2 ≤ N) {i : Nat} (hi : i + 1 < k) (hiN : i + 1 < N) :
    Arc (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) (i, 1) (i + 1, N + (i + 1)) :=
  Or.inr ((expArc_iff hk hN).mpr ⟨mem_ringA.mpr ⟨hi, by simp; omega, by simp; omega⟩, by simp, by simp [prev]⟩)

theorem walk_ringPath (hk : 1 ≤ k) (hN : 2 ≤ N) (hkN : k ≤ N) {z : Agent} : ∀ (r i : Nat), i + r ≤ k →
    (1 ≤ r → Arc (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) (i + r - 1, 1) z) →
    ∀ e ∈ steps (ringPath N i r ++ [z]), Arc (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) e.1 e.2
  | 0, i, _, _ => by simp [ringPath, steps]
  | r + 1, i, hir, hz => by
    obtain ⟨l, hl⟩ := upPath_last i (N + i) (N + i)
    have hup := walk_upPath (k := k) (N := N) (sh := sh) (i := i) (by omega) (p := N + i) (f := N + i) (by omega)
      (by omega) (Nat.le_refl _)
    rw [hl] at hup
    have hup' : ∀ e ∈ steps (l ++ [(i, 1)]), Arc (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) e.1 e.2 :=
      fun e he => Or.inl (hup e he)
    cases r with
    | zero =>
      have hz' := hz (Nat.le_refl _)
      rw [show i + (0 + 1) - 1 = i by omega] at hz'
      intro e he
      simp only [ringPath, hl, List.append_nil, List.append_assoc, List.singleton_append] at he
      exact walk_join (l2 := []) hup' hz' (by simp [steps]) e he
    | succ r =>
      obtain ⟨l2, hl2⟩ := ringPath_head (N := N) (by omega) (i := i + 1) (r := r + 1) (by omega)
      have ih := walk_ringPath hk hN hkN (r + 1) (i + 1) (by omega) (fun _ => by
        rw [show i + 1 + (r + 1) - 1 = i + (r + 1 + 1) - 1 by omega]
        exact hz (by omega))
      rw [hl2] at ih
      intro e he
      have hsplit : ringPath N i (r + 1 + 1) = upPath i (N + i) (N + i) ++ ringPath N (i + 1) (r + 1) := rfl
      rw [hsplit, hl, hl2] at he
      simp only [List.append_assoc, List.cons_append] at he
      exact walk_join hup' (arc_next hk hN (by omega) (by omega)) ih e he

/-- **The ring cycle is a cycle of `D⁺`.** -/
theorem dcycle_ringCycle (hk : 2 ≤ k) (hN : 2 ≤ N) (hkN : k ≤ N) :
    DCycle (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) (ringCycle k N) := by
  obtain ⟨l, hl⟩ := ringPath_head (N := N) (by omega) (i := 0) (r := k) (by omega)
  have htake : (ringCycle k N).take 1 = [(0, N + 0)] := by rw [ringCycle, hl]; rfl
  refine ⟨by rw [ringCycle, hl]; simp, nodup_ringPath, ?_⟩
  have hw := walk_ringPath (sh := sh) (by omega) hN hkN (z := (0, N + 0)) k 0 (by omega) (fun _ =>
    Or.inr ((expArc_iff (by omega) hN).mpr ⟨mem_ringA.mpr ⟨by simp; omega, by simp; omega, by simp; omega⟩,
      by simp, by simp [prev]⟩))
  intro e he
  unfold cycArcs at he
  rw [htake] at he
  exact hw e he

theorem nodup_map_filter {β γ : Type} (L : List (β × β)) (p : β × β → Bool) (g : β → γ)
    (hL : (L.map Prod.snd).Nodup)
    (hinj : ∀ e ∈ L, ∀ e' ∈ L, p e = true → p e' = true → g e.2 = g e'.2 → e.2 = e'.2) :
    ((L.filter p).map (fun e => g e.2)).Nodup := by
  rw [List.nodup_iff_pairwise_ne, List.pairwise_map]
  rw [List.nodup_iff_pairwise_ne, List.pairwise_map] at hL
  exact (hL.filter p).imp_of_mem fun {a b} ha hb hne e => by
    have ha' := List.mem_filter.mp ha
    have hb' := List.mem_filter.mp hb
    exact hne (hinj a ha'.1 b hb'.1 ha'.2 hb'.2 e)

theorem nodup_heads {α : Type} {c : List α} (h : c.Nodup) : ((cycArcs c).map Prod.snd).Nodup := by
  cases c with
  | nil => simp [cycArcs, steps]
  | cons u c =>
    rw [cycArcs_snd]
    have h' := List.nodup_cons.mp h
    refine List.nodup_append.mpr ⟨h'.2, by simp, fun a ha b hb e => ?_⟩
    rw [List.mem_singleton.mp hb] at e
    exact h'.1 (e ▸ ha)

theorem mem_heads {α : Type} {c : List α} {e : α × α} (he : e ∈ cycArcs c) : e.2 ∈ c := by
  cases c with
  | nil => simp [cycArcs, steps] at he
  | cons u c =>
    have : e.2 ∈ (cycArcs (u :: c)).map Prod.snd := List.mem_map_of_mem he
    rw [cycArcs_snd] at this
    rcases List.mem_append.mp this with h | h
    · exact List.mem_cons_of_mem _ h
    · rw [List.mem_singleton.mp h]
      exact List.mem_cons_self

/-- The heads of the exposure arcs of the ring cycle are the leaves `(j, N + j)`. -/
theorem head_ringCycle (hk : 2 ≤ k) (hN : 2 ≤ N) (hkN : k ≤ N) {e : Agent × Agent}
    (he : e ∈ cycArcs (ringCycle k N))
    (hE : expArcB (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) e.1 e.2 = true) :
    e.2 ∈ ringA k N ∧ N ≤ e.2.2 ∧ e.2.1 < k ∧ e.2.2 = N + e.2.1 := by
  obtain ⟨hx, hl, -⟩ := (expArc_iff (by omega) hN).mp (expArcB_iff.mp hE)
  obtain ⟨-, h2, h3⟩ := mem_ringPath (mem_heads he)
  obtain ⟨-, -, h4⟩ := mem_upPath h3
  refine ⟨hx, hl, by omega, by omega⟩

theorem label_inj {x x' : Agent} (hx : x.1 < k) (hx' : x'.1 < k) (h1 : x.2 = N + x.1) (h2 : x'.2 = N + x'.1)
    (e : label k N sh x = label k N sh x') : x = x' := by
  obtain ⟨j, p⟩ := x
  obtain ⟨j', p'⟩ := x'
  simp only at hx hx' h1 h2
  subst h1 h2
  cases sh with
  | true =>
    simp only [label, ↓reduceIte, Good.pool.injEq, Nat.add_sub_cancel_left, Nat.mod_eq_of_lt hx,
      Nat.mod_eq_of_lt hx'] at e
    subst e
    rfl
  | false =>
    simp only [label, Bool.false_eq_true, ↓reduceIte, Good.lab.injEq] at e
    rw [e.1]

/-- **The ring cycle has distinct labels**: its `k` exposure arcs enter the leaves `(j, N + j)`, `j < k`, whose labels
are different (`lab j (N + j)`, or `pool j`). -/
theorem labels_ringCycle (hk : 2 ≤ k) (hN : 2 ≤ N) (hkN : k ≤ N) :
    (labels (ringP k N sh) (ringA k N) [] (ringY k N) (ringG k N sh) (ringCycle k N)).Nodup := by
  apply nodup_map_filter _ _ _ (nodup_heads nodup_ringPath)
  intro e he e' he' hE hE' heq
  obtain ⟨hx, hl, h1, h2⟩ := head_ringCycle hk hN hkN he hE
  obtain ⟨hx', hl', h1', h2'⟩ := head_ringCycle hk hN hkN he' hE'
  rw [hOf_leaf (by omega) hN hx hl, hOf_leaf (by omega) hN hx' hl'] at heq
  exact label_inj h1 h1' h2 h2' heq

/-- For `k = 2`, `d = 1`: `(0, 2) → o_0 → (1, 3) → o_1 → (0, 2)`. -/
theorem ringCycle_2_2 : ringCycle 2 2 = [(0, 2), (0, 1), (1, 3), (1, 1)] := rfl

/-- For `k = 3`, `d = 2`: three paths of length two up the trees, joined by three exposure arcs. -/
theorem ringCycle_3_4 :
    ringCycle 3 4 = [(0, 4), (0, 2), (0, 1), (1, 5), (1, 2), (1, 1), (2, 6), (2, 3), (2, 1)] := rfl

/-! ## The family of the paper: `N = 2^d` leaves per tree -/

theorem two_le_pow {d : Nat} (hd : 1 ≤ d) : 2 ≤ 2 ^ d := by
  have := Nat.pow_le_pow_right (n := 2) (by omega) hd
  simpa using this

/-- **The ring family of `paper/k3-simple` §6.4** (`gen_tree(k, d, shared)`, both label modes), for all `k ≥ 2`,
`d ≥ 1` with `k ≤ 2^d`: a well-formed core instance and a valid state satisfying (P), with exactly `k` free agents,
in which no free agent is a valid absorber; every cycle of `D⁺` (with distinct labels or not) uses exactly `k`
exposure arcs; and a cycle of `D⁺` with distinct labels exists. -/
theorem gen_tree_ring {k d : Nat} (sh : Bool) (hk : 2 ≤ k) (hd : 1 ≤ d) (hkd : k ≤ 2 ^ d) :
    WF (ringP k (2 ^ d) sh) (ringA k (2 ^ d)) (ringG k (2 ^ d) sh) ∧ (ringA k (2 ^ d)).Nodup ∧
      (ringG k (2 ^ d) sh).Nodup ∧
      Valid (ringP k (2 ^ d) sh) (ringA k (2 ^ d)) (ringG k (2 ^ d) sh) (ringY k (2 ^ d)) [] ∧
      PropP (ringP k (2 ^ d) sh) (ringA k (2 ^ d)) [] (ringY k (2 ^ d)) (ringG k (2 ^ d) sh) ∧
      ((ringA k (2 ^ d)).filter (freeB (ringP k (2 ^ d) sh) (ringA k (2 ^ d)) [] (ringY k (2 ^ d)))).length = k ∧
      (¬ ∃ o H, Free (ringP k (2 ^ d) sh) (ringA k (2 ^ d)) [] (ringY k (2 ^ d)) o ∧
        Absorber (ringP k (2 ^ d) sh) (ringA k (2 ^ d)) (ringG k (2 ^ d) sh) (ringY k (2 ^ d)) [] o H) ∧
      (∀ c, DCycle (ringP k (2 ^ d) sh) (ringA k (2 ^ d)) [] (ringY k (2 ^ d)) (ringG k (2 ^ d) sh) c →
        nExp (ringP k (2 ^ d) sh) (ringA k (2 ^ d)) [] (ringY k (2 ^ d)) (ringG k (2 ^ d) sh) c = k) ∧
      (∃ c, DCycle (ringP k (2 ^ d) sh) (ringA k (2 ^ d)) [] (ringY k (2 ^ d)) (ringG k (2 ^ d) sh) c ∧
        (labels (ringP k (2 ^ d) sh) (ringA k (2 ^ d)) [] (ringY k (2 ^ d)) (ringG k (2 ^ d) sh) c).Nodup) := by
  have hN := two_le_pow hd
  exact ⟨wf (by omega) hN, nodup_ringA, nodup_ringG, valid, propP (by omega) hN, nFree (by omega),
    no_free_absorber hk hN hkd, fun _ hc => nExp_eq hk hN hc,
    ⟨_, dcycle_ringCycle hk hN hkd, labels_ringCycle hk hN hkd⟩⟩

end Rings
end DE
end EFX

/-! ## Axiom certificates (audited by `check.sh`) -/

#print axioms EFX.DE.Rings.expArcB_iff
#print axioms EFX.DE.Rings.DCycle.two_le
#print axioms EFX.DE.Rings.countP_ring
#print axioms EFX.DE.Rings.nodup_ringA
#print axioms EFX.DE.Rings.nodup_ringG
#print axioms EFX.DE.Rings.prefers_iff
#print axioms EFX.DE.Rings.free_iff
#print axioms EFX.DE.Rings.valid
#print axioms EFX.DE.Rings.wf
#print axioms EFX.DE.Rings.propP
#print axioms EFX.DE.Rings.exposed_iff
#print axioms EFX.DE.Rings.hOf_leaf
#print axioms EFX.DE.Rings.nFree
#print axioms EFX.DE.Rings.no_free_absorber
#print axioms EFX.DE.Rings.not_completable
#print axioms EFX.DE.Rings.free_absorber_of_lt
#print axioms EFX.DE.Rings.no_free_absorber_iff
#print axioms EFX.DE.Rings.needArc_iff
#print axioms EFX.DE.Rings.expArc_iff
#print axioms EFX.DE.Rings.arc_cases
#print axioms EFX.DE.Rings.nExp_eq
#print axioms EFX.DE.Rings.nExp_eq_of_labels
#print axioms EFX.DE.Rings.dcycle_ringCycle
#print axioms EFX.DE.Rings.labels_ringCycle
#print axioms EFX.DE.Rings.ringCycle_2_2
#print axioms EFX.DE.Rings.ringCycle_3_4
#print axioms EFX.DE.Rings.gen_tree_ring
