#!/usr/bin/env python3
"""Summary tables of the DL13 runs (compute/k4-dl13; k4/dl13.c, k4/dl13_run.py, k4/dl13_hunt.py). EVIDENCE only.

usage: python3 k4/dl13_summary.py [--note=TEXT ...] [@GROUP] NAME=TABLES.json ... [@GROUP NAME=TABLES.json ...] > summary.md
Each TABLES.json is written by `k4/dl13_run.py --tables=...` or `k4/dl13_hunt.py --tables=...`.
Prints, in Markdown: per input the profiles, the f >= 1 states (min-frozen P with def > 0 on a profile with f >= 1),
the DL13 failures and the branches; then, summed over the inputs, the branch by obstruction class (each class counted
at every state whose signature contains it; dl2.c's signature: the exposure classes w.r.t. the best owners, D2,
allfrozen, PM), by the nearest repair distance k, by f, and the move types available at the T3-only states; with
"@GROUP" arguments, these tables are printed per group of inputs.

Branches: "T1 only" = some T1 move lowers the deficit and no T3 move does; "T3 only" = some T3 move does and no T1
move does (the T1-stuck states); "both"; "none" = DL13 fails. "T3h only" = the only improving R_13 moves are role
swaps with a helper."""
import json, sys
from collections import Counter, defaultdict

CLS = ['e1', 'e2', 'e3', 'fO', 'G', 'G1', 'L', 'O', 'D2', 'allfrozen', 'PM']
BR = ['T1 only', 'T3 only', 'both', 'none']


def cat(br):
    if br == 'none': return 'none'
    t1 = 'T1' in br.split('+'); t3 = any(b.startswith('T3') for b in br.split('+'))
    return 'both' if t1 and t3 else ('T1 only' if t1 else 'T3 only')


def fmt(x): return f'{x:,}'


def main(argv):
    ins = []; group = 'all inputs'; groups = []; notes = []; distinct = None
    for a in argv:
        if a.startswith('--note='):            # a paragraph printed under the table of the inputs
            notes.append(a[7:]); continue
        if a.startswith('--distinct-fail='):   # the number of distinct failing states (the inputs may overlap)
            distinct = int(a.split('=', 1)[1]); continue
        if a.startswith('@'):                  # "@TITLE" starts a group: the tables below are printed per group
            group = a[1:]; continue
        name, path = a.rsplit('=', 1)
        ins.append((name, json.load(open(path)), group))
        if group not in groups: groups.append(group)
    print('# DL13 runs: summary (generated by `k4/dl13_summary.py`)\n')
    print('Counts are states: min-frozen P with def(P) > 0 on a profile whose fewest frozen agents is f >= 1 (the scope of '
          'Conjecture DL13); f = 0 states are listed apart (Theorem Z covers them; R_13 is not meant to hold there). '
          'Branches as in `k4/dl13_summary.py`.\n')
    print('| input | command | profiles (ω ≥ 1) | f ≥ 1 states | DL13 fails | T1 only | T3 only | (T3h only) | both | f = 0 states (R_13 fails) |')
    print('|---|---|---|---|---|---|---|---|---|---|')
    tot = Counter()
    for name, d, _ in ins:
        c = d['counters']
        for k, v in c.items():
            if k != 'maxmin': tot[k] += v
        print(f"| {name} | `{d.get('command', '')}` | {fmt(c['prof'])} ({fmt(c['om1'])}) | {fmt(c['st1'])} | **{fmt(c['fail1'])}** | "
              f"{fmt(c['t1only'])} | {fmt(c['t3only'])} | {fmt(c['t3hOnly'])} | {fmt(c['both'])} | {fmt(c['st0'])} ({fmt(c['fail0'])}) |")
    failcell = (f"**{fmt(distinct)} distinct** ({fmt(tot['fail1'])} summed)" if distinct is not None else f"**{fmt(tot['fail1'])}**")
    print(f"| **sum over the inputs** (they overlap) | | {fmt(tot['prof'])} ({fmt(tot['om1'])}) | {fmt(tot['st1'])} | {failcell} | {fmt(tot['t1only'])} | "
          f"{fmt(tot['t3only'])} | {fmt(tot['t3hOnly'])} | {fmt(tot['both'])} | {fmt(tot['st0'])} ({fmt(tot['fail0'])}) |\n")
    print(f"(Profiles are summed over the inputs; the hunts and samples may repeat profiles. Anomalies (a one-agent move "
          f"of a frozen agent, impossible by Lemma 1(a)): {tot['anom']}.)\n")
    for t in notes: print(t + '\n')

    for scope in groups:
        B = Counter(); G = Counter(); Y = Counter(); F = Counter(); sig = Counter()
        for name, d, g in ins:
            if g != scope: continue
            for key, cnt in d['tab'].items():
                t, rest = key.split(' ', 1)
                parts = rest.split('|')
                if t == 'B':
                    f, s, br = parts; cb = cat(br)
                    F[(f, cb)] += cnt; sig[(s, cb)] += cnt
                    cl = s.split(',') if s else []
                    for c in CLS:
                        if c in cl: B[(c, cb)] += cnt
                    if not any(c in cl for c in CLS): B[('(empty)', cb)] += cnt
                    if 'PM' in cl:
                        B[('PM-states', cb)] += cnt
                    if br == 'T3h': B[('T3h only', 'T3 only')] += cnt
                elif t == 'G':
                    f, k, br = parts; G[(k, cat(br))] += cnt
                elif t == 'Y':
                    f, br, ty = parts; Y[(cat(br), ty)] += cnt
        print(f'# {scope}\n')
        print(f'## Branch by obstruction class ({scope})\n')
        print('A state counts under every class of its signature (so rows overlap).\n')
        print('| class | T1 only | T3 only | both | none | T3 share |')
        print('|---|---|---|---|---|---|')
        for c in CLS + ['(empty)']:
            row = [B[(c, b)] for b in BR]
            if sum(row): print(f"| {c} | " + ' | '.join(fmt(x) for x in row) + f" | {100 * row[1] / sum(row):.1f}% |")
        print()
        print('## Branch by f\n')
        print('| f | T1 only | T3 only | both | none |')
        print('|---|---|---|---|---|')
        for f in sorted({f for f, _ in F}, key=int):
            print(f'| {f} | ' + ' | '.join(fmt(F[(f, b)]) for b in BR) + ' |')
        print()
        print('## Branch by the nearest repair distance k (any min-frozen P′ with a smaller deficit, `dl2.c`\'s k(P))\n')
        print('| k | T1 only | T3 only | both | none |')
        print('|---|---|---|---|---|')
        for k in sorted({k for k, _ in G}, key=int):
            print(f'| {k} | ' + ' | '.join(fmt(G[(k, b)]) for b in BR) + ' |')
        print()
        print('## Move types available, by branch (a state counts once per type present among its improving R_13 moves)\n')
        print('T1: rel (gives up goods only), grow (adds goods only), pool (swaps with the junk). T3: x\'s new base from J '
              '(xJ), from J + B_z (xZ), using the helper\'s base (xH); helper: none (h-), pure release (hR), swap with the '
              'pool (hJ), takes a good of B_z (hZ).\n')
        print('| type | T1 only | T3 only | both |')
        print('|---|---|---|---|')
        for ty in sorted({ty for _, ty in Y}):
            print(f'| {ty} | ' + ' | '.join(fmt(Y[(b, ty)]) for b in BR[:3]) + ' |')
        print()
        print('## The 40 most frequent signatures (states)\n')
        print('| signature | T1 only | T3 only | both | none |')
        print('|---|---|---|---|---|')
        tops = Counter()
        for (s, b), cnt in sig.items(): tops[s] += cnt
        for s, _ in tops.most_common(40):
            print(f'| {s or "-"} | ' + ' | '.join(fmt(sig[(s, b)]) for b in BR) + ' |')
        print()


if __name__ == '__main__':
    main(sys.argv[1:])
