"""Builds results/k4_m_portfolio/TABLE.md from the JSON summaries written by k4/lemmam_portfolio.py --out=...
(and the hunt summaries of k4/lemmam_hunt.py, if any).
Usage: lemmam_table.py [DIR]   (default results/k4_m_portfolio; the datasets are listed in ORDER below)"""
import glob, json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lemmam_portfolio import CANDS, VARS, SETS, PREDS, ALIAS

ORDER = ['n2', 'n3', 'n4_1_all', 'n4_2_all', 'n4_s50', 'n4_s2000', 'n5_s20', 'n5_s200', 'H', 'suite']
DESC = {
    'M': 'Lemma M: some first agent in K0 ∪ K1',
    'M_K0': 'control: some first agent in K0',
    'M_bt': 'some big-top agent ⇒ some big-top agent in K0 ∪ K1',
    'M_bt1': 'exactly one big-top q ⇒ q in K0 ∪ K1',
    'M_nobt': 'no big-top, some shared top ⇒ some shared-top agent in K0 ∪ K1',
    'M_gap': 'argmax a − (b + c) (representative values, ties lowest index) in K0 ∪ K1',
    'M_gapn': 'argmax (a − b − c)/(a + b + c + d) (scale-free) in K0 ∪ K1',
    'M_kappa': 'some first agent with M1: |σ_F| ≤ κ₀ (or ω ≤ 0)',
    'M_def1': 'some first agent with M2 = Lemma KR (o = r) "in particular" form (δ ≤ 1)',
    'M_12': 'some first agent with M1 or M2',
    'M_K0KR': 'some first agent in K0 or with Lemma KR\'s full bound (o = r)',
    'M_K0KRo': 'some first agent in K0 or with Lemma KR\'s full bound for some owner o',
    'M_bt12': 'some big-top ⇒ some big-top agent with M1 or M2',
    'M_nobt0': 'no big-top, no shared top (vacuous case of M_nobt) ⇒ M',
    'M_btK0KR': 'some big-top ⇒ some big-top agent in K0 or with KR\'s full bound (o = r)',
    'M_K0KRw': 'some first agent in K0, or with KR\'s full bound (o = r), or with a rotation into r reaching ω′ ≤ 0',
    'M_K0KRwo': 'some first agent in K0, or with KR (some owner), or with a rotation reaching ω′ ≤ 0',
}


def fmt(x): return f'{x:,}'


def main():
    D = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'results', 'k4_m_portfolio')
    S = {}
    for f in glob.glob(os.path.join(D, '*.json')):
        k = os.path.splitext(os.path.basename(f))[0]
        o = json.load(open(f))
        if 'counters' in o and not k.startswith('hunt'): S[k] = o
    keys = [k for k in ORDER if k in S] + sorted(k for k in S if k not in ORDER)
    L = ['# Lemma M portfolio: candidates × datasets', '',
         'Generated by `k4/lemmam_table.py` from the JSON summaries of `k4/lemmam_portfolio.py` in this directory. '
         'EVIDENCE only (PROMPT.md §5 rule 3). Classes K0, K1 are `k4/rulef.c`\'s (included unchanged; `-Y1`: Lemma K '
         'with Remark 4\'s kept-out sets; policies need-shrinking and envy-free, as rule RK). Each cell: '
         '**failures** / applicable profiles. "tight": exactly one allowed agent satisfies the predicate; "only": exactly '
         'one first agent of the whole profile is in K0 ∪ K1 and it is the candidate\'s.', '']
    L.append('Datasets: ' + '; '.join(f'`{k}` = {S[k]["label"]}' for k in keys) + '.')
    L.append('')
    L.append('| candidate | statement | ' + ' | '.join(f'`{k}`' for k in keys) + ' |')
    L.append('|---|---|' + '---|' * len(keys))
    for al, c in ALIAS.items():
        row = [f'**{al}** (`{c}`)', DESC[al]]
        for k in keys:
            t = S[k]['counters'].get(c)
            row.append('–' if not t else f'**{fmt(t[1])}** / {fmt(t[0])}')
        L.append('| ' + ' | '.join(row) + ' |')
    L += ['', '## The whole grid: allowed set × predicate (failures, summed over all datasets)', '',
          'Sets: all; bt = big-top agents (if any); bt1 = the big-top agent (if exactly one); nobt = agents sharing their '
          'top (no big-top agent, some shared top); nobt0 = all (no big-top, no shared top); gap / gapn = the argmax of '
          'a − (b + c) / of (a − b − c)/(a + b + c + d); btp = big-top agents with the fewest private goods; shp = '
          'shared-top agents with the fewest private goods (no big-top); bt2 = big-top agents (if two or more). '
          'Predicates (some policy): W = K0 ∪ K1; K0; M1; KRb (Lemma KR, o = r, δ ≤ 1 form = M2); M1|KRb; K0|KRa (KR\'s '
          'full bound, o = r); K0|KRo (KR, any owner); K0|KRb; K0|KRa|Rw (or a rotation along a need chain into r to a state '
          'with ω′ ≤ 0 and no 3-good base: no owner needed); K0|KRo|Rwo (the same with any owner / any chain end). Cell: **failures** / applicable over every dataset of '
          'this table (datasets overlap in kind, not in profiles); per-dataset counts are in the JSON files.', '']
    L.append('| set | ' + ' | '.join(f'`{q}`' for q in PREDS) + ' |')
    L.append('|---|' + '---|' * len(PREDS))
    for a in SETS:
        row = [f'`{a}`']
        for q in PREDS:
            c = f'{a}:{q}'; ap = fl = 0
            for k in keys:
                t = S[k]['counters'].get(c)
                if t: ap += t[0]; fl += t[1]
            row.append(f'**{fmt(fl)}** / {fmt(ap)}' if fl else f'0 / {fmt(ap)}')
        L.append('| ' + ' | '.join(row) + ' |')
    L += ['', '## Slack of the survivors (tight / only, per dataset)', '']
    L.append('| candidate | ' + ' | '.join(f'`{k}`' for k in keys) + ' |')
    L.append('|---|' + '---|' * len(keys))
    for c in CANDS:
        if any(S[k]['counters'].get(c, [0, 0])[1] for k in keys): continue
        row = [f'`{c}`']
        for k in keys:
            t = S[k]['counters'].get(c)
            row.append('–' if not t else f'{fmt(t[2])} / {fmt(t[3])}')
        L.append('| ' + ' | '.join(row) + ' |')
    L += ['', 'Profiles with exactly one first agent in K0 ∪ K1 (tightM) and with no agent in K0 but some in K1 (K1only): ' +
          '; '.join(f'`{k}`: {fmt(S[k]["counters"].get("tightM", [0])[0])} / {fmt(S[k]["counters"].get("K1only", [0])[0])}' for k in keys), '']
    L += ['## Exchange partners', '',
          'For every (profile, first agent a) with a in neither K0 nor K1, the partner a′ read off a\'s run (policy N = '
          'need-shrinking, E = envy-free): x1 the exposed frozen 4-good agents, x2 the leader of r\'s block, x3 the ends of '
          'the need chains from the x1 agents, x3b from r\'s block leader (exposed, frozen), x3c from any exposed frozen '
          'agent, x4 r itself. Cell: pairs / undefined (no partner) / **none works** (defined, no partner in K0 ∪ K1) / all work.', '']
    L.append('| variant | ' + ' | '.join(f'`{k}`' for k in keys) + ' |')
    L.append('|---|' + '---|' * len(keys))
    for v in VARS:
        if not any(v in S[k]['counters'] for k in keys): continue
        row = [v]
        for k in keys:
            t = S[k]['counters'].get(v)
            row.append('–' if not t else f'{fmt(t[0])} / {fmt(t[1])} / **{fmt(t[0] - t[1] - t[2])}** / {fmt(t[3])}')
        L.append('| ' + ' | '.join(row) + ' |')
    L += ['', '## (G2), C40 and checks of the proved lemmas', '',
          'Counts over (profile, first agent) pairs: g2bad = LB⁺\'s bad case in the envy-free run with no exposed 4-good '
          'agent; g2 = (G2) (r four goods, exposed after the rotation along every chain k* → r); g2W = (G2) and the agent '
          'is in K0 ∪ K1 anyway; c40 = Corollary C₄⁰\'s hypothesis; c40notW = C40 but not in K0 ∪ K1 (C40 ⊆ K0 ∪ K1 is '
          'proved: must be 0); profc40 / profnoc40 = profiles with some / no C40 agent (on profnoc40 Step 1 of §6 gives '
          'nothing and Step 3 is needed); m1notK0 (Lemma S: M1 ⇒ K0), krnotW (Lemma KR: KR ⇒ K0 ∪ K1), kronotW: must be 0; '
          'wK1 = agents in K1 but not K0, wK1KR of them with a Lemma KR rotation (o = r), wK1noKR without; wK1noKRRw: '
          'neither KR nor a rotation into r reaching ω′ ≤ 0; wK1noKRoRwo: neither KR for any owner nor a rotation to ω′ ≤ 0.', '']
    ks2 = ['g2bad', 'g2', 'g2W', 'c40', 'c40notW', 'profc40', 'profnoc40', 'm1notK0', 'krnotW', 'kronotW', 'wK0', 'wK1', 'wK1KR', 'wK1noKR', 'wK1noKRRw', 'wK1noKRoRwo']
    L.append('| dataset | ' + ' | '.join(ks2) + ' |')
    L.append('|---|' + '---|' * len(ks2))
    for k in keys:
        L.append(f'| `{k}` | ' + ' | '.join(fmt(S[k]['counters'].get(x, [0])[0]) for x in ks2) + ' |')
    L += ['', '## Smallest failures', '']
    allf = {}
    for k in keys:
        for nm, o in S[k].get('smallest', {}).items():
            if nm not in allf or tuple(allf[nm][0]) > tuple(o['key']): allf[nm] = (o['key'], o['line'], k)
    inv = {v: k for k, v in ALIAS.items()}
    for nm in sorted(allf, key=lambda x: (x.startswith('partner'), x not in inv, x)):
        key, line, k = allf[nm]
        L.append(f'- **{nm}**' + (f' ({inv[nm]})' if nm in inv else '') + f' (dataset `{k}`, n = {key[0]}, m = {key[1]}): `{line[:700]}`')
    L.append('')
    H = sorted(glob.glob(os.path.join(D, 'hunt*.json')))
    if H:
        L += ['## Phase 3: annealing hunts (`k4/lemmam_hunt.py`)', '',
              'Each task anneals the profile of one core (or seed profile) against one candidate: score = 64 × (allowed '
              'agents satisfying the predicate) + (first agents in K0 ∪ K1); a failure stops the walk. "best" is the '
              'lowest score reached (64 + 1 = 65: the candidate\'s agent was the only first agent in K0 ∪ K1); for a '
              'partner variant, "best" < 1000 means some first agent outside K0 ∪ K1 with a defined partner was reached.', '',
              '| hunt | candidate | walks | failures | best score | smallest failure |', '|---|---|---|---|---|---|']
        for f in H:
            o = json.load(open(f))
            for c, r in o.get('results', {}).items():
                sm = r.get('smallest')
                L.append(f'| `{os.path.basename(f)}` | `{c}` | {r["tasks"]} | **{r["failures"]}** | {r["best_score"]} | '
                         + (f'`{sm[:300]}`' if sm else '–') + ' |')
        L.append('')
    L += ['## Runs', '']
    for k in keys:
        o = S[k]
        L.append(f'- `{k}`: {o["label"]}; options `{" ".join(o.get("options", []))}`; tasks {o.get("tasks")}; CPU {o.get("cpu_seconds")} s; '
                 f'source sha {o["sha"]}; rulef.c sha256 {o["rulef_sha256"][:16]}…')
    open(os.path.join(D, 'TABLE.md'), 'w').write('\n'.join(L) + '\n')
    print('\n'.join(L))


if __name__ == '__main__':
    main()
