"""Additive order types of k goods (k = 3, 4): the weak orders on subsets that positive additive values realize.

An agent with relevant goods g_0..g_{k-1} and positive values v compares disjoint sets only (EFX₀ compares own bundle
with part of another bundle), and v(S) >= v(T) iff v(S - T) >= v(T - S); so its behavior is fixed by the sign vector
    sigma(v) = ( sign(v(S) - v(T)) : {S, T} disjoint, nonempty )          (25 pairs for k = 4, 6 for k = 3).
A type is a sign vector realized by some v in (0, inf)^k: a face of the arrangement of the hyperplanes v(S) = v(T)
inside the open orthant.

Completeness (why a finite grid finds every type). Add the k coordinate hyperplanes. Each face F in the open orthant is
a relatively open pointed cone; its closure is generated by extreme rays, which are 1-dimensional faces of the
arrangement: solutions of k - 1 independent equations with coefficients in {-1, 0, 1}, so each has an integer generator
whose coordinates are (k-1)x(k-1) minors of a {-1,0,1} matrix, at most 4 for k = 4 (2 for k = 3). If dim F = d, pick
d linearly independent extreme rays of cl F: the open simplicial cone they span is open in span F and lies in cl F, so
it lies in F; its point "sum of the d rays" is an integer vector in F with coordinates <= 4d <= 16 (k = 4; <= 6 for
k = 3). So the grid [1, 16]^4 meets every face. The script checks this twice: (a) the grid, (b) all sums of <= k
distinct rays (computed from the minors) that are positive; the two sets of sign vectors must be equal, and a larger
grid must find nothing new.

Usage: order_types.py [--write]      prints counts; --write stores k4/order_types.json (types with integer reps)."""
import itertools, json, math, os, sys

def pairs(k):
    """Unordered pairs {S, T} of disjoint nonempty subsets of range(k), as bitmask pairs (S < T)."""
    out = []
    for S in range(1, 1 << k):
        for T in range(S + 1, 1 << k):
            if S & T == 0: out.append((S, T))
    return out

def val(v, S):
    return sum(x for g, x in enumerate(v) if S >> g & 1)

def sign(x): return (x > 0) - (x < 0)

def sigma(v, P):
    return tuple(sign(val(v, S) - val(v, T)) for S, T in P)

def grid_types(k, B):
    P, seen = pairs(k), {}
    for v in itertools.product(range(1, B + 1), repeat=k):
        s = sigma(v, P)
        key = (max(v), sum(v), v)                                     # smallest representative: max, then sum, then lex
        if s not in seen or key < seen[s][0]: seen[s] = (key, v)
    return {s: kv[1] for s, kv in seen.items()}

def det(M):
    if len(M) == 1: return M[0][0]
    return sum((-1) ** c * M[0][c] * det([row[:c] + row[c + 1:] for row in M[1:]]) for c in range(len(M)))

def rays(k):
    """Integer generators of the 1-dimensional faces in the closed orthant (arrangement plus coordinate hyperplanes)."""
    P = pairs(k)
    normals = [[(S >> g & 1) - (T >> g & 1) for g in range(k)] for S, T in P]
    normals += [[int(g == h) for g in range(k)] for h in range(k)]
    R = set()
    for rows in itertools.combinations(normals, k - 1):
        r = [(-1) ** c * det([row[:c] + row[c + 1:] for row in rows]) for c in range(k)]   # null vector (minors)
        if not any(r): continue
        if all(x <= 0 for x in r): r = [-x for x in r]
        if not all(x >= 0 for x in r): continue
        g = math.gcd(*r); R.add(tuple(x // g for x in r))
    return sorted(R)

def ray_sum_types(k):
    P, R, out = pairs(k), rays(k), set()
    for d in range(1, k + 1):
        for sub in itertools.combinations(R, d):
            v = [sum(c) for c in zip(*sub)]
            if all(x > 0 for x in v): out.add(sigma(v, P))
    return R, out

def balanced(v):
    return max(v) < sum(v) - max(v)

def canon(v):
    """Canonical form under permutations of the goods (sign vector of the sorted-down representative is not enough
    with ties, so take the lexicographically least sign vector over all permutations)."""
    P = pairs(len(v))
    return min(sigma([v[p] for p in perm], P) for perm in itertools.permutations(range(len(v))))

def summary(k, bound):
    T = grid_types(k, bound)
    R, T2 = ray_sum_types(k)
    big = grid_types(k, bound + 4 if k == 4 else bound + 6)
    assert set(T) == T2 == set(big), "grid and ray sums disagree"
    reps = list(T.values())
    strict = [v for s, v in T.items() if 0 not in s]
    bal = [v for v in reps if balanced(v)]
    bal_strict = [v for v in strict if balanced(v)]
    dec = lambda L: [v for v in L if all(v[g] > v[g + 1] for g in range(k - 1))]
    unl = lambda L: len({canon(v) for v in L})
    print(f"k={k}: rays {len(R)} (max coordinate {max(max(r) for r in R)}); faces in the open orthant: grid [1,{bound}]^{k}"
          f" = ray sums = grid [1,{bound + (4 if k == 4 else 6)}]^{k}: {len(T)}")
    print(f"  labeled types: all {len(reps)}, strict {len(strict)}, balanced {len(bal)}, balanced strict {len(bal_strict)}")
    print(f"  up to permuting goods: all {unl(reps)}, strict {unl(strict)}, balanced {unl(bal)}, balanced strict {unl(bal_strict)}")
    print(f"  strict with v_0 > ... > v_{k-1}: {len(dec(strict))} ({len(dec(bal_strict))} balanced);"
          f" largest coordinate of a smallest representative: all {max(max(v) for v in reps)},"
          f" balanced strict {max(max(v) for v in bal_strict)}")
    return T

if __name__ == '__main__':
    out = {}
    for k, bound in ((3, 6), (4, 16)):
        T = summary(k, bound)
        P = pairs(k)
        out[str(k)] = {'pairs': P, 'types': [{'rep': list(v), 'strict': 0 not in s, 'balanced': balanced(v)}
                                            for s, v in sorted(T.items(), key=lambda sv: (sv[1][::-1]))]}
        if k == 4:
            print("  the balanced strict types with v_0 > v_1 > v_2 > v_3 (smallest reps; a, b, c, d = goods 0..3):")
            for s, v in sorted(T.items(), key=lambda sv: sv[1]):
                if 0 in s or not balanced(v) or not all(v[g] > v[g + 1] for g in range(3)): continue
                subs = sorted(range(1, 16), key=lambda S: (val(v, S), S))
                name = lambda S: ''.join('abcd'[g] for g in range(4) if S >> g & 1)
                print(f"    {v}: " + ' < '.join(name(S) for S in subs))
    if '--write' in sys.argv:
        with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'order_types.json'), 'w') as f:
            json.dump(out, f, separators=(',', ':'))
        print("wrote k4/order_types.json")
